name: CI

on:
  push:
  pull_request:

jobs:
  # Run lowest tests first as a batch
  tests-lowest:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]

    name: PHP ${{ matrix.php }} - prefer-lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch 10 commits or Scrutinizer will throw ("Failed to retrieve commit parents. If you use a shallow git checkout, please checkout at least a depth of one."), see: RepositoryIntrospector at scrutinizer-ci/ocular GitHub repository
          # 10 commits is an arbitrary value that is more than 1 commit
          fetch-depth: 10

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: composer update --prefer-lowest --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Upload Code Coverage
        continue-on-error: true
        run: vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover || true

  # Run stable tests after lowest tests complete
  tests-stable:
    runs-on: ubuntu-latest
    needs: tests-lowest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]

    name: PHP ${{ matrix.php }} - prefer-stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch 10 commits or Scrutinizer will throw ("Failed to retrieve commit parents. If you use a shallow git checkout, please checkout at least a depth of one."), see: RepositoryIntrospector at scrutinizer-ci/ocular GitHub repository
          # 10 commits is an arbitrary value that is more than 1 commit
          fetch-depth: 10

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: PHP Security Checker
        uses: symfonycorp/security-checker-action@v5

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Upload Code Coverage
        continue-on-error: true
        run: vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover || true
